# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20170615_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencestranslation',
            name='bio',
        ),
    ]
