# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 11:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170305_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
