# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_track_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.CharField(default='0:00', max_length=4),
        ),
    ]
