# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 15:40
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations
import django.db.models.deletion
import pavel_kinal.preferences.forms


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20170615_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotranslation',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='videotranslation',
            name='language',
            field=pavel_kinal.preferences.forms.LanguageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='preferences.Language', verbose_name='Язык'),
        ),
    ]
